/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedInvestmentRouteImport } from './routes/_authenticated/investment'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedWithdrawalRouteImport } from './routes/_authenticated/withdrawal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestmentRoute = AuthenticatedInvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawalRoute = AuthenticatedWithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/home': typeof AuthenticatedHomeRoute
  '/investment': typeof AuthenticatedInvestmentRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/withdrawal': typeof AuthenticatedWithdrawalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/home': typeof AuthenticatedHomeRoute
  '/investment': typeof AuthenticatedInvestmentRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/withdrawal': typeof AuthenticatedWithdrawalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/investment': typeof AuthenticatedInvestmentRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/withdrawal': typeof AuthenticatedWithdrawalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/deposit'
    | '/home'
    | '/investment'
    | '/records'
    | '/rewards'
    | '/support'
    | '/tasks'
    | '/team'
    | '/withdrawal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/deposit'
    | '/home'
    | '/investment'
    | '/records'
    | '/rewards'
    | '/support'
    | '/tasks'
    | '/team'
    | '/withdrawal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/deposit'
    | '/_authenticated/home'
    | '/_authenticated/investment'
    | '/_authenticated/records'
    | '/_authenticated/rewards'
    | '/_authenticated/support'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/_authenticated/withdrawal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investment': {
      id: '/_authenticated/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof AuthenticatedInvestmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdrawal': {
      id: '/_authenticated/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof AuthenticatedWithdrawalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInvestmentRoute: typeof AuthenticatedInvestmentRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWithdrawalRoute: typeof AuthenticatedWithdrawalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInvestmentRoute: AuthenticatedInvestmentRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWithdrawalRoute: AuthenticatedWithdrawalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
