// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";

export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(async ({ next }) =>
  next(),
);
